import 'dart:io';

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:open_mail/open_mail.dart';
import 'package:package_info_plus/package_info_plus.dart';
import 'package:period_tracker/constants.dart';
import 'package:period_tracker/models/period_model.dart';
import 'package:period_tracker/models/settings_model.dart';
import 'package:period_tracker/models/user_model.dart';
import 'package:period_tracker/providers/period_provider.dart';
import 'package:period_tracker/providers/settings_provider.dart';
import 'package:period_tracker/providers/user_provider.dart';
import 'package:period_tracker/services/application_data_service.dart';
import 'package:period_tracker/services/encryption_service.dart';
import 'package:period_tracker/services/notification_service.dart';
import 'package:period_tracker/shared_preferences/shared_preferences.dart';
import 'package:period_tracker/utils/file_helper.dart';
import 'package:provider/provider.dart';
import 'package:restart_app/restart_app.dart';

class RestoreDataPreviewPage extends StatefulWidget {
  final List sharedFiles;
  const RestoreDataPreviewPage({super.key, required this.sharedFiles});

  @override
  State<RestoreDataPreviewPage> createState() => _RestoreDataPreviewPageState();
}

class _RestoreDataPreviewPageState extends State<RestoreDataPreviewPage> {
  late bool _onBoardingComplete;
  Map<String, dynamic>? _sharedFileContent;
  bool _loading = true;
  String? _error;
  bool _restoreError = false;
  bool _showErrorDetails = false;
  bool _alertShown = false;

  String? _name;
  List _periods = [];

  Future<void> _initialize() async {
    final isComplete = await getOnboardingComplete();
    if (!mounted) return;
    setState(() {
      _onBoardingComplete = isComplete;
      _loading = true;
      _error = null;
    });
    await clearFileShared();

    // try parsing the file
    try {
      // check if the file path is valid
      final String? filePath = widget.sharedFiles[0].path;
      if (filePath == null || filePath.isEmpty) {
        setState(() {
          _sharedFileContent = null;
          _loading = false;
          _error = '$kBackupFileName file not found';
        });
        return;
      }

      // check if the file exists
      final File file = File(filePath);
      if (!await file.exists()) {
        setState(() {
          _sharedFileContent = null;
          _loading = false;
          _error = '$kBackupFileName file not found';
        });
        return;
      }

      // read the file content
      final String? fileContent = await FileHelper.readFileContent(filePath);
      if (fileContent == null || fileContent.isEmpty) {
        setState(() {
          _sharedFileContent = null;
          _loading = false;
          _error = 'Backup file is empty';
        });
        return;
      }
      _sharedFileContent = ApplicationDataService().parseBackupFile(
        fileContent,
      );
      if (_sharedFileContent == null) {
        setState(() {
          _sharedFileContent = null;
          _loading = false;
          _error = 'Failed to parse backup file';
        });
        return;
      }

      // verify json file was generated by this app
      final String? appId = _sharedFileContent!['app'] as String?;
      if (appId == null || appId != kPackageName) {
        context.go(_onBoardingComplete ? '/' : '/onboarding');
        return;
      }

      // verify backup data structure and content
      final bool validBackupData = ApplicationDataService().isBackupDataValid(
        _sharedFileContent!,
      );
      if (!validBackupData) {
        setState(() {
          _sharedFileContent = null;
          _loading = false;
          _error = 'Invalid backup file format';
        });
        return;
      }

      // verify version compatibility
      final PackageInfo packageInfo = await PackageInfo.fromPlatform();
      final bool compatible = ApplicationDataService()
          .verifyVersionCompatibility(
            _sharedFileContent!['version'] as String,
            packageInfo.version,
          );
      if (!compatible) {
        setState(() {
          _sharedFileContent = null;
          _loading = false;
          _error = 'Incompatible backup file version';
        });
        return;
      }

      setState(() {
        _sharedFileContent = _sharedFileContent!;
        _loading = false;
        _name = _sharedFileContent!['database']['user']['name'];
        _periods = (_sharedFileContent!['database']['periods'])
            .map((e) => Period.fromMap(e as Map<String, dynamic>))
            .toList();
      });

      // show alert if onboarding is complete and we have a valid shared file
      WidgetsBinding.instance.addPostFrameCallback(
        (_) => _maybeShowOnboardingAlert(),
      );
    } catch (e) {
      setState(() {
        _sharedFileContent = null;
        _loading = false;
        _error = e.toString();
      });
    }
  }

  void _maybeShowOnboardingAlert() {
    if (!mounted) return;
    if (_alertShown) return;
    if (_onBoardingComplete) {
      _alertShown = true;
      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (context) => AlertDialog(
          title: const Text('Existing data detected'),
          content: const Text(
            'We detected you already have an existing account on this device. Restoring from this backup file will replace your current data.\n'
            'Do you wish to continue?',
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.of(context).pop();
                context.go(_onBoardingComplete ? '/' : '/onboarding');
              },
              style: TextButton.styleFrom(
                foregroundColor: Theme.of(context).colorScheme.tertiary,
              ),
              child: const Text('No, exit restore'),
            ),
            TextButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              child: const Text('Continue'),
            ),
          ],
          backgroundColor: Theme.of(context).colorScheme.primaryContainer,
        ),
      );
    }
  }

  @override
  void initState() {
    super.initState();
    _initialize();
  }

  void _restoreData() async {
    if (_sharedFileContent == null) return; // should not happen
    setState(() => _loading = true);

    try {
      final success = await ApplicationDataService().restoreFromBackup(
        _sharedFileContent!,
      );

      // wait a moment to show the spinner
      await Future.delayed(const Duration(milliseconds: 2000));

      if (success) {
        await setDisplayRestoreSuccess(true);

        // schedule notifications
        final User? user = Provider.of<UserProvider>(
          context,
          listen: false,
        ).user;
        Settings? settings = Provider.of<SettingsProvider>(
          context,
          listen: false,
        ).settings;

        DateTime? nextPeriodStartDate =
            Provider.of<PeriodProvider>(
              context,
              listen: false,
            ).getNextPeriodDate(
              settings?.predictionMode == 'dynamic',
              user?.cycleLength,
            );

        await NotificationService().scheduleNotificationsForNextPeriod(
          nextPeriodStartDate,
          settings!.notificationDaysBefore,
          settings.notificationTime,
        );

        setState(() {
          _loading = false;
        });

        // restart app to go to home page
        Restart.restartApp();
        return;
      }
    } catch (e) {
      setState(() {
        _loading = false;
        _restoreError = true;
        _error = e.toString();
      });
    }
  }

  void showNoMailAppsDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text("Cannot Open Email App"),
          content: const Text(
            "No email apps installed on this device. Please install an email app to contact support.",
          ),
          actions: [
            TextButton(
              child: const Text("OK"),
              onPressed: () {
                Navigator.pop(context);
              },
            ),
          ],
          backgroundColor: Theme.of(context).colorScheme.primaryContainer,
        );
      },
    );
  }

  Future<void> openEmail() async {
    final PackageInfo packageInfo = await PackageInfo.fromPlatform();
    final String encodedContent = _sharedFileContent != null
        ? EncryptionService().base64Encode(_sharedFileContent.toString())
        : 'N/A';

    final EmailContent emailContent = EmailContent(
      to: [kContactEmail],
      subject: 'Issue with Period Tracker',
      body:
          '''
Hello,

I'm having an issue with restoring data in the Period Tracker app. Here are the details:

[Error: ${_error ?? 'Unknown error'}]
[Restore error: ${_restoreError.toString()}]
[Timestamp: ${DateTime.now()}]
[Version: ${packageInfo.version}+${packageInfo.buildNumber}]
[Device: ${Platform.operatingSystem}]
[OS version: ${Platform.operatingSystemVersion}]
[Backup content: $encodedContent]''',
    );
    OpenMailAppResult result;

    try {
      result = await OpenMail.composeNewEmailInMailApp(
        nativePickerTitle: 'Select email app to contact support',
        emailContent: emailContent,
      );

      if (!result.didOpen && !result.canOpen) {
        showNoMailAppsDialog(context);
      }
    } catch (e) {
      ScaffoldMessenger.of(context).clearSnackBars();
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('An error occurred while trying to open email app'),
          behavior: SnackBarBehavior.floating,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final int periodCount = _periods.length;
    final String restoreSummary = periodCount == 0
        ? 'All your data is ready to be restored.'
        : periodCount == 1
        ? 'All your data, including 1 logged period, is ready to be restored.'
        : 'All your data, including $periodCount logged periods, is ready to be restored.';
    final String restoreSummaryOverwrite = periodCount == 0
        ? 'All your data will be restored, replacing your existing data.'
        : periodCount == 1
        ? 'All your data, including 1 logged period, will be restored, replacing your existing data.'
        : 'All your data, including $periodCount logged periods, will be restored, replacing your existing data.';
    final String errorText = _restoreError
        ? 'An error occurred while restoring your data. Please restart the app try again. In case that doesn\'t work, try exporting the file on your old phone again.'
        : 'There is an issue with your $kBackupFileName file. Please restart the app try again. In case that doesn\'t work, try exporting the file on your old phone again.';

    return Scaffold(
      body: Center(
        child: SafeArea(
          child: _loading
              ? const CircularProgressIndicator()
              : Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    if (_error != null)
                      Column(
                        children: [
                          Text(
                            'Error :(',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Theme.of(context).colorScheme.onSurface,
                              fontSize: Theme.of(
                                context,
                              ).textTheme.headlineSmall?.fontSize,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Column(
                              children: [
                                Text(
                                  errorText,
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Theme.of(
                                      context,
                                    ).colorScheme.onSurface,
                                  ),
                                ),
                                Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    Text(
                                      'If the issue persists ',
                                      style: Theme.of(
                                        context,
                                      ).textTheme.bodyMedium,
                                    ),
                                    TextButton(
                                      style: TextButton.styleFrom(
                                        padding: EdgeInsets.zero,
                                        minimumSize: const Size(0, 0),
                                        tapTargetSize:
                                            MaterialTapTargetSize.shrinkWrap,
                                        alignment: Alignment.centerLeft,
                                      ),
                                      onPressed: () => openEmail(),
                                      child: Text(
                                        'contact support',
                                        style: TextStyle(
                                          decoration: TextDecoration.underline,
                                          decorationColor: Theme.of(
                                            context,
                                          ).colorScheme.onSurface,
                                          color: Theme.of(
                                            context,
                                          ).colorScheme.onSurface,
                                        ),
                                      ),
                                    ),
                                    Text('.'),
                                  ],
                                ),
                              ],
                            ),
                          ),
                          ElevatedButton(
                            onPressed: () {
                              context.go(
                                _onBoardingComplete ? '/' : '/onboarding',
                              );
                            },
                            child: Text('Exit restore'),
                          ),
                          const SizedBox(height: 8),
                          TextButton(
                            style: TextButton.styleFrom(
                              padding: EdgeInsets.zero,
                              minimumSize: const Size(0, 0),
                              tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                            ),
                            onPressed: () => setState(
                              () => _showErrorDetails = !_showErrorDetails,
                            ),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Text(
                                  _showErrorDetails
                                      ? 'Hide details'
                                      : 'Show details',
                                  style: TextStyle(
                                    color: Theme.of(
                                      context,
                                    ).colorScheme.tertiary,
                                  ),
                                ),
                                const SizedBox(width: 6),
                                Icon(
                                  _showErrorDetails
                                      ? Icons.expand_less
                                      : Icons.expand_more,
                                  color: Theme.of(context).colorScheme.tertiary,
                                  size: 18,
                                ),
                              ],
                            ),
                          ),
                          AnimatedCrossFade(
                            firstChild: const SizedBox.shrink(),
                            secondChild: Padding(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 16.0,
                                vertical: 8.0,
                              ),
                              child: Text(
                                _error ?? 'Unknown error',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Theme.of(context).colorScheme.tertiary,
                                ),
                              ),
                            ),
                            crossFadeState: _showErrorDetails
                                ? CrossFadeState.showSecond
                                : CrossFadeState.showFirst,
                            duration: const Duration(milliseconds: 200),
                          ),
                          const SizedBox(width: 6),
                        ],
                      ),
                    if (_error == null)
                      Column(
                        children: [
                          SizedBox(height: 30),
                          if (_onBoardingComplete)
                            Column(
                              children: [
                                Text(
                                  _name == null || _name!.isEmpty
                                      ? 'Welcome!'
                                      : 'Welcome $_name!',
                                  textAlign: TextAlign.center,
                                  style: Theme.of(
                                    context,
                                  ).textTheme.headlineSmall,
                                ),
                                const SizedBox(height: 14),
                                Padding(
                                  padding: const EdgeInsets.symmetric(
                                    horizontal: 8.0,
                                  ),
                                  child: Text(
                                    textAlign: TextAlign.center,
                                    '$restoreSummaryOverwrite\n'
                                    'Only proceed if you are sure you want to replace your existing data with the data in the $kBackupFileName file.',
                                  ),
                                ),
                                ElevatedButton(
                                  onPressed: _restoreData,
                                  child: const Text('Restore my data'),
                                ),
                                const SizedBox(height: 50),
                                InkWell(
                                  splashColor: Theme.of(
                                    context,
                                  ).colorScheme.primary.withValues(alpha: 0.33),
                                  onTap: () => context.go('/'),
                                  borderRadius: BorderRadius.circular(8),
                                  child: Padding(
                                    padding: const EdgeInsets.all(8.0),
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      crossAxisAlignment:
                                          CrossAxisAlignment.center,
                                      children: [
                                        const Text(
                                          'Want to keep your existing data?',
                                        ),
                                        Text(
                                          'Exit restore',
                                          style: TextStyle(
                                            color: Theme.of(
                                              context,
                                            ).colorScheme.primary,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ],
                            )
                          else
                            Column(
                              children: [
                                Text(
                                  _name == null || _name!.isEmpty
                                      ? 'Welcome back!'
                                      : 'Welcome back $_name!',
                                  textAlign: TextAlign.center,
                                  style: Theme.of(
                                    context,
                                  ).textTheme.headlineSmall,
                                ),
                                const SizedBox(height: 14),
                                Padding(
                                  padding: const EdgeInsets.symmetric(
                                    horizontal: 8.0,
                                  ),
                                  child: Text(
                                    restoreSummary,
                                    textAlign: TextAlign.center,
                                  ),
                                ),
                                ElevatedButton(
                                  onPressed: _restoreData,
                                  child: const Text('Restore my data'),
                                ),
                                const SizedBox(height: 50),
                                InkWell(
                                  splashColor: Theme.of(
                                    context,
                                  ).colorScheme.primary.withValues(alpha: 0.33),
                                  onTap: () => context.go('/onboarding'),
                                  borderRadius: BorderRadius.circular(8),
                                  child: Padding(
                                    padding: const EdgeInsets.all(8.0),
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      crossAxisAlignment:
                                          CrossAxisAlignment.center,
                                      children: [
                                        const Text(
                                          'Want to start fresh instead?',
                                        ),
                                        Text(
                                          'Start fresh',
                                          style: TextStyle(
                                            color: Theme.of(
                                              context,
                                            ).colorScheme.primary,
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                              ],
                            ),
                        ],
                      ),
                  ],
                ),
        ),
      ),
    );
  }
}
