# `flutter analyze`
# https://dart.dev/tools#ides-and-editors
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

linter:
  # `package:flutter_lints/flutter.yaml`
  # https://dart.dev/lints.
  # `// ignore: name_of_lint`
  # `// ignore_for_file: name_of_lint`
  rules:
    sort_pub_dependencies: true
    directives_ordering: true
    # avoid_print: false  
    # prefer_single_quotes: true