name: period_tracker
description: "Period tracking app"
publish_to: 'none'

version: 1.2.0+21

environment:
  sdk: ^3.8.1

# `flutter pub upgrade --major-versions` - upgrade package dependencies to the latest versions
# `flutter pub outdated` - see dependencies with newer versions available.
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  go_router: ^16.0.0
  google_fonts: ^6.3.1
  http: ^1.5.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  table_calendar: ^3.2.0
  timezone: ^0.10.1
  open_mail: ^1.2.0
  restart_app: ^1.3.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets useful links:
  # https://flutter.dev/to/resolution-aware-images
  # https://flutter.dev/to/asset-from-package
  assets:
    - assets/images/logo.png
    - assets/images/tutorials/transfer-profile-page.png
    - assets/images/tutorials/transfer-dialog.png
    - assets/images/tutorials/transfer-share.png
    - assets/images/tutorials/transfer-gmail.png
    - assets/images/tutorials/restore-gmail.png
    - assets/images/tutorials/restore-files-app.png
    - assets/images/tutorials/restore-files-downloads.png
    - assets/images/tutorials/restore-open-with.png
    - assets/images/tutorials/restore-open.png
    - assets/images/tutorials/restore-preview.png
    - assets/images/tutorials/restore-success.png

  # Fonts useful links and examples:
  # https://flutter.dev/to/font-from-package
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700