enum DogBreed {
  affenpinscher("affenpinscher", "Affenpinscher"),
  african_wild("african/wild", "African Wild"),
  airedale("airedale", "Airedale"),
  akita("akita", "Akita"),
  appenzeller("appenzeller", "Appenzeller"),
  australian_kelpie("australian/kelpie", "Australian Kelpie"),
  australian_shepherd("australian/shepherd", "Australian Shepherd"),
  bakharwal_indian("bakharwal/indian", "Indian Bakharwal"),
  basenji("basenji", "Basenji"),
  beagle("beagle", "Beagle"),
  bluetick("bluetick", "Bluetick"),
  borzoi("borzoi", "Borzoi"),
  bouvier("bouvier", "Bouvier"),
  boxer("boxer", "Boxer"),
  brabancon("brabancon", "Brabancon"),
  briard("briard", "Briard"),
  buhund_norwegian("buhund/norwegian", "Norwegian Buhund"),
  bulldog_boston("bulldog/boston", "Boston Bulldog"),
  bulldog_english("bulldog/english", "English Bulldog"),
  bulldog_french("bulldog/french", "French Bulldog"),
  bullterrier_staffordshire(
    "bullterrier/staffordshire",
    "Staffordshire Bullterrier",
  ),
  cattledog_australian("cattledog/australian", "Australian Cattledog"),
  cavapoo("cavapoo", "Cavapoo"),
  chihuahua("chihuahua", "Chihuahua"),
  chippiparai_indian("chippiparai/indian", "Indian Chippiparai"),
  chow("chow", "Chow"),
  clumber("clumber", "Clumber"),
  cockapoo("cockapoo", "Cockapoo"),
  collie_border("collie/border", "Border Collie"),
  coonhound("coonhound", "Coonhound"),
  corgi_cardigan("corgi/cardigan", "Cardigan Corgi"),
  cotondetulear("cotondetulear", "Coton de Tulear"),
  dachshund("dachshund", "Dachshund"),
  dalmatian("dalmatian", "Dalmatian"),
  dane_great("dane/great", "Great Dane"),
  danish_swedish("danish/swedish", "Danish Swedish"),
  deerhound_scottish("deerhound/scottish", "Scottish Deerhound"),
  dhole("dhole", "Dhole"),
  dingo("dingo", "Dingo"),
  doberman("doberman", "Doberman"),
  elkhound_norwegian("elkhound/norwegian", "Norwegian Elkhound"),
  entlebucher("entlebucher", "Entlebucher"),
  eskimo("eskimo", "Eskimo Dog"),
  finnish_lapphund("finnish/lapphund", "Finnish Lapphund"),
  frise_bichon("frise/bichon", "Bichon Frise"),
  gaddi_indian("gaddi/indian", "Indian Gaddi"),
  german_shepherd("german/shepherd", "German Shepherd"),
  greyhound_indian("greyhound/indian", "Indian Greyhound"),
  greyhound_italian("greyhound/italian", "Italian Greyhound"),
  groenendael("groenendael", "Groenendael"),
  havanese("havanese", "Havanese"),
  hound_afghan("hound/afghan", "Afghan Hound"),
  hound_basset("hound/basset", "Basset Hound"),
  hound_blood("hound/blood", "Blood Hound"),
  hound_english("hound/english", "English Hound"),
  hound_ibizan("hound/ibizan", "Ibizan Hound"),
  hound_plott("hound/plott", "Plott Hound"),
  hound_walker("hound/walker", "Walker Hound"),
  husky("husky", "Husky"),
  keeshond("keeshond", "Keeshond"),
  kelpie("kelpie", "Kelpie"),
  kombai("kombai", "Kombai"),
  komondor("komondor", "Komondor"),
  kuvasz("kuvasz", "Kuvasz"),
  labradoodle("labradoodle", "Labradoodle"),
  labrador("labrador", "Labrador"),
  leonberg("leonberg", "Leonberg"),
  lhasa("lhasa", "Lhasa"),
  malamute("malamute", "Malamute"),
  malinois("malinois", "Malinois"),
  maltese("maltese", "Maltese"),
  mastiff_bull("mastiff/bull", "Bull Mastiff"),
  mastiff_english("mastiff/english", "English Mastiff"),
  mastiff_indian("mastiff/indian", "Indian Mastiff"),
  mastiff_tibetan("mastiff/tibetan", "Tibetan Mastiff"),
  mexicanhairless("mexicanhairless", "Mexican Hairless"),
  mix("mix", "Mix"),
  mountain_bernese("mountain/bernese", "Bernese Mountain Dog"),
  mountain_swiss("mountain/swiss", "Swiss Mountain Dog"),
  mudhol_indian("mudhol/indian", "Indian Mudhol"),
  newfoundland("newfoundland", "Newfoundland"),
  otterhound("otterhound", "Otterhound"),
  ovcharka_caucasian("ovcharka/caucasian", "Caucasian Ovcharka"),
  papillon("papillon", "Papillon"),
  pariah_indian("pariah/indian", "Indian Pariah"),
  pekinese("pekinese", "Pekinese"),
  pembroke("pembroke", "Pembroke"),
  pinscher_miniature("pinscher/miniature", "Miniature Pinscher"),
  pitbull("pitbull", "Pitbull"),
  pointer_german("pointer/german", "German Pointer"),
  pointer_germanlonghair("pointer/germanlonghair", "German Longhair Pointer"),
  pomeranian("pomeranian", "Pomeranian"),
  poodle_medium("poodle/medium", "Medium Poodle"),
  poodle_miniature("poodle/miniature", "Miniature Poodle"),
  poodle_standard("poodle/standard", "Standard Poodle"),
  poodle_toy("poodle/toy", "Toy Poodle"),
  pug("pug", "Pug"),
  puggle("puggle", "Puggle"),
  pyrenees("pyrenees", "Pyrenees"),
  rajapalayam_indian("rajapalayam/indian", "Indian Rajapalayam"),
  redbone("redbone", "Redbone"),
  retriever_chesapeake("retriever/chesapeake", "Chesapeake Retriever"),
  retriever_curly("retriever/curly", "Curly Retriever"),
  retriever_flatcoated("retriever/flatcoated", "Flatcoated Retriever"),
  retriever_golden("retriever/golden", "Golden Retriever"),
  ridgeback_rhodesian("ridgeback/rhodesian", "Rhodesian Ridgeback"),
  rottweiler("rottweiler", "Rottweiler"),
  rough_collie("rough/collie", "Rough Collie"),
  saluki("saluki", "Saluki"),
  samoyed("samoyed", "Samoyed"),
  schipperke("schipperke", "Schipperke"),
  schnauzer_giant("schnauzer/giant", "Giant Schnauzer"),
  schnauzer_miniature("schnauzer/miniature", "Miniature Schnauzer"),
  segugio_italian("segugio/italian", "Italian Segugio"),
  setter_english("setter/english", "English Setter"),
  setter_gordon("setter/gordon", "Gordon Setter"),
  setter_irish("setter/irish", "Irish Setter"),
  sharpei("sharpei", "Shar Pei"),
  sheepdog_english("sheepdog/english", "English Sheepdog"),
  sheepdog_indian("sheepdog/indian", "Indian Sheepdog"),
  sheepdog_shetland("sheepdog/shetland", "Shetland Sheepdog"),
  shiba("shiba", "Shiba"),
  shihtzu("shihtzu", "Shih Tzu"),
  spaniel_blenheim("spaniel/blenheim", "Blenheim Spaniel"),
  spaniel_brittany("spaniel/brittany", "Brittany Spaniel"),
  spaniel_cocker("spaniel/cocker", "Cocker Spaniel"),
  spaniel_irish("spaniel/irish", "Irish Spaniel"),
  spaniel_japanese("spaniel/japanese", "Japanese Spaniel"),
  spaniel_sussex("spaniel/sussex", "Sussex Spaniel"),
  spaniel_welsh("spaniel/welsh", "Welsh Spaniel"),
  spitz_indian("spitz/indian", "Indian Spitz"),
  spitz_japanese("spitz/japanese", "Japanese Spitz"),
  springer_english("springer/english", "English Springer"),
  stbernard("stbernard", "St. Bernard"),
  terrier_american("terrier/american", "American Terrier"),
  terrier_andalusian("terrier/andalusian", "Andalusian Terrier"),
  terrier_australian("terrier/australian", "Australian Terrier"),
  terrier_bedlington("terrier/bedlington", "Bedlington Terrier"),
  terrier_border("terrier/border", "Border Terrier"),
  terrier_boston("terrier/boston", "Boston Terrier"),
  terrier_cairn("terrier/cairn", "Cairn Terrier"),
  terrier_dandie("terrier/dandie", "Dandie Terrier"),
  terrier_fox("terrier/fox", "Fox Terrier"),
  terrier_irish("terrier/irish", "Irish Terrier"),
  terrier_kerryblue("terrier/kerryblue", "Kerry Blue Terrier"),
  terrier_lakeland("terrier/lakeland", "Lakeland Terrier"),
  terrier_norfolk("terrier/norfolk", "Norfolk Terrier"),
  terrier_norwich("terrier/norwich", "Norwich Terrier"),
  terrier_patterdale("terrier/patterdale", "Patterdale Terrier"),
  terrier_russell("terrier/russell", "Russell Terrier"),
  terrier_scottish("terrier/scottish", "Scottish Terrier"),
  terrier_sealyham("terrier/sealyham", "Sealyham Terrier"),
  terrier_silky("terrier/silky", "Silky Terrier"),
  terrier_tibetan("terrier/tibetan", "Tibetan Terrier"),
  terrier_toy("terrier/toy", "Toy Terrier"),
  terrier_welsh("terrier/welsh", "Welsh Terrier"),
  terrier_westhighland("terrier/westhighland", "West Highland Terrier"),
  terrier_wheaten("terrier/wheaten", "Wheaten Terrier"),
  terrier_yorkshire("terrier/yorkshire", "Yorkshire Terrier"),
  tervuren("tervuren", "Tervuren"),
  vizsla("vizsla", "Vizsla"),
  waterdog_spanish("waterdog/spanish", "Spanish Waterdog"),
  weimaraner("weimaraner", "Weimaraner"),
  whippet("whippet", "Whippet"),
  wolfhound_irish("wolfhound/irish", "Irish Wolfhound");

  final String value; // API key
  final String display; // UI label

  const DogBreed(this.value, this.display);
}
